# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Commit
  jobs: 
  - job: Build
    steps:
    - script: |
        wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
        sudo apt-get update
        sudo apt-get install esl-erlang
    - script: |
        sudo apt-get install elixir
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix format --check-formatted
        mix credo --strict
        mix test --exclude acceptance
        echo mix format --checked-formatted
        echo Add other tasks to build, test, and deploy your project
      
