[[section-solution-strategy]]
:source-highlighter: highlightjs
:highlightjs-languages: elixir
:main_sourcepath: ../../lib/

== Lösungsstrategie

[role="arc42help"]
****
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.
****

[source, javascript, linenums]
----
# This program prints hello, world ! // <1>
printf('Hello, world!') //<2>
----
<1> bla bla
<2> bla bal

[source, elixir, linenums, indent=2]
----
defp deliver(to, body) do
  require Logger #<1>
  Logger.debug(body) #<2>
  {:ok, %{to: to, body: body}}
end
----

[source, elixir, linenums, indent=2]
----
include::{main_sourcepath}gigalixirdeploy/accounts.ex[tags=GetUserEmail]
----


== Test
.Test Diagram 1 without 2nd level include
plantuml::../../diagrams/test.puml[]


