name: TestAndDeploy
on: 
  push:
    branches: [master]
  workflow_dispatch:

jobs: 
  test: 
    runs-on: ubuntu-18.04
    services: 
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy: 
      matrix:
        otp: [24.0.1]
        elixir: [1.12.0]
    steps:
    - uses: actions/checkout@v2
    - run: sudo pip3 install gigalixir --ignore-installed six
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 14.17.0
    - name: Cache Elixir deps
      uses: actions/cache@v1
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Cache Elixir _build
      uses: actions/cache@v1
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }} 
    - name: Cache Node modules
      uses: actions/cache@v1
      id: node-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('assets/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install deps
      run: |
        mix deps.get
        npm install --prefix assets
        npm run deploy --prefix assets

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Run Unittests 
      run: mix test

    - name: Cache PLT 
      uses: actions/cache@v1
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Create PLT
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt
    - name: Run Dialyzer
      run: mix dialyzer --no-check --halt-exit-status        
      
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.1

    - uses: mhanberg/gigalixir-action@v0.6.1
      with:
        GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
        GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP }}
        MIGRATIONS: false
