name: TestStage
on:
  workflow_run:
    workflows:
      - CommitStage
    types:
      - completed
jobs:
  on-success:
    name: Success Step
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
      - run: echo 'succes'
  on-failure:
    name: Failure Step
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - run: echo 'failure'

